### ISSUE TITLE
Generate Perspective not finding properties.

### ISSUE THREAD

**Issue by swainjo** [neo4j-apps/neo4j-bloom#12]
When I run a generate perspective on a graph for two node types Bloom does not populate the properties.

I can share the graph privately to help diagnose the issue.

**Comment by ckanz** [comment]
Thanks for reaching out @swainjo. Could you let me know the version of Neo4j and of Bloom you are using (you can see the version of Bloom when opening the "About Bloom" panel on the button in the bottom-left corner)? Also, do some nodes in the graph have more than one label?

I am asking because are aware of an issue in Bloom 1.3.0 with certain Neo4j versions where properties are not appearing in the perspective when some nodes in the graph have more than one label. A fix for this is already in the pipeline and will go out in a patch release soon.

If you are using a different version of Bloom or if all nodes in the graph only have a single label each, could you run `call db.schema.nodeTypeProperties` on your database and check if you see all expected properties in the result? (please note that this procedure only runs on databases with version 3.5 or higher)

**Comment by swainjo** [comment]
Hi Clemens,

seems like this is the issue as most nodes have multiple labels and versions are those you mention. Keep me posted on the fix.

regards,
js

Neo4j 3.5.17
Bloom 1.3

**Comment by ckanz** [comment]
Thanks @swainjo, will let you know once the fix is live.

**Comment by ckanz** [comment]
@swainjo Bloom 1.3.1 has been released. The release contains a fix of the issue of node properties not showing when nodes have multiple labels. Please let me know in case you are still running into problems with generating a perspective after the update.

**Comment by swainjo** [comment]
looking good :-)
