### ISSUE TITLE
Feature Request: Export as PNG or PDF

### ISSUE THREAD

**Issue by mdileep** [neo4j-apps/neo4j-bloom#28]
It would be nice to have a feature to export the Neo4j Bloom Scene as PNG or PDF.

**Comment by anutan76** [comment]
@mdileep we have recently started collecting feedback and feature requests for Bloom over at https://neo4j-bloom.canny.io/feature-requests. There is a link in the Help section of Bloom for your future reference. Would you mind adding this request there, so others can see and upvote as well?

**Comment by ckanz** [comment]
Hi @mdileep, it is possible by now to export scene has PNG and CSV using the "Export" button in the top right corner: https://neo4j.com/docs/bloom-user-guide/current/bloom-tutorial/export-data/

I will be closing this issue since it's been some time since the last reply. If you have any issues with Bloom, please feel free to raise a new issue here or on Canny https://neo4j-aura.canny.io/explore
