### ISSUE TITLE
Feature Request: Option to expand nodes based on Search phrases

### ISSUE THREAD

**Issue by thor-issuu** [neo4j-apps/neo4j-bloom#30]
In some cases you would want to expand a node based on a query defined in a Search phrase. It would be great if that could be done through the expand menu on the node. The Search phrases relevant to a node could be determined by the input options to a Search phrase.

**Comment by tbwiss** [comment]
Hej @thor-issuu! Thanks for reaching out and your interest in Bloom!
We'll take this feature request into consideration for the upcoming development iterations.

**Comment by vitorhortajoinanalytics** [comment]
Can we expect to have this feature in future releases? It would be super useful to expand nodes using search phrases!

**Comment by vitorhortajoinanalytics** [comment]
Can we expect to have this feature in future releases? It would be super useful to expand nodes using search phrases!

**Comment by vitorhorta** [comment]
Can we expect to have this feature in future releases? It would be super useful to expand nodes using search phrases!

**Comment by tbwiss** [comment]
@vitorhorta glad to hear that you are interested in this feature too! We are actually currently hashing out the details concerning it. As you might understand, I can't make any promises about it being included in a future release but I'll mention your interest.

**Comment by ckanz** [comment]
Hi @vitorhorta, hi @thor-issuu,
glad to say that we've implemented the requested feature, which is called "Scene actions". You can find out more about them here: https://neo4j.com/docs/bloom-user-guide/current/bloom-tutorial/scene-actions/

I will be closing this issue since it's been some time since the last reply. If you have any issues with Bloom, please feel free to raise a new issue here or on Canny https://neo4j-aura.canny.io/explore
