### ISSUE TITLE
Information about releases not available

### ISSUE THREAD

**Issue by pjljvandelaar** [neo4j-apps/neo4j-bloom#34]
Dear Neo4j-bloom developers,

Today Neo4j informed me of a new version of Neo4j-bloom.
This new version solved a bug related to making connection and having short time outs.

I installed this version, yet I am no longer able to reread the text.

Also on this website, I can find no information on version 1.6.2.
version 1.6.1 seems to be the latest version according to this link: https://github.com/neo4j-devtools/neo4j-bloom/releases

For Neo4j I can query the release notes in the tool:
![image](https://user-images.githubusercontent.com/18348654/121307292-21d93c80-c900-11eb-8f78-dfc44021560d.png)
![image](https://user-images.githubusercontent.com/18348654/121307263-1b4ac500-c900-11eb-8397-ca5390904675.png)

I would like to have the same functionality for Neo4j-bloom.
Somewhere in this menu:
![image](https://user-images.githubusercontent.com/18348654/121307421-433a2880-c900-11eb-97cd-933b33d801ec.png)

Thanks in advance!

Greetings,
 Pierre

**Comment by joknelid** [comment]
Hi!

The release notes for the 1.6.2 release should be available now in this repo - we just had a bit of a crunch yesterday in order to get the release out as soon as possible because it was impacting multiple users so we didn't have time to complete the release process until today. But this is really an exception, normally we will do the complete process in one go so that this repository will be updated etc.

About showing release notes for apps in Neo4j Desktop, I think that sounds reasonable to me and I will forward that to the Neo4j Desktop team

Have a great day!
Jens

**Comment by ckanz** [comment]
Hi @pjljvandelaar! It is now possible to see the release notes of Bloom in Desktop. You can also find the current and previous release notes on https://neo4j.com/release-notes/bloom/

I will be closing this issue since it's been some time since the last reply. If you have any issues with Bloom, please feel free to raise a new issue here or on Canny https://neo4j-aura.canny.io/explore
