### ISSUE TITLE
Bloom Desktop version connectivity to PowerBI

### ISSUE THREAD

**Issue by rohinibaraskar** [neo4j-apps/neo4j-bloom#44]
We havent bought licensed version of Bloom yet , But we want to try if we can connect Bloom to Power BI .

**Comment by GlacialBoy** [comment]
Hello @rohinibaraskar !
Neo4j Bloom can only connect to a Neo4j database, so if you want to visualise that data in Bloom the first step is importing the data in a Neo4j database.

In order to import data from Power BI you can use the appropriate Neo4j Connector, which is available here [Neo4j Download Center](https://neo4j.com/download-center/#integrations)

If it is not what you're trying to do please describe your use case,
Thanks!

**Comment by rohinibaraskar** [comment]
hi @GlacialBoy 
Lets say , I have few "Search Phrases " saved query templates in Bloom and I want sperate URL for each that search phrase How can I achieve that.
I can render home page of bloom in browser but I wanted to load query output of particular search phrase in browser whenever I specify that particular URL
Could you please assist?
as I am going to specify that each URL in Power BI to show graph visualization.

**Comment by rohinibaraskar** [comment]
its working
