### ISSUE TITLE
Bloom Perspective ICONs and Text settings are not setting permanently 

### ISSUE THREAD

**Issue by rohinibaraskar** [neo4j-apps/neo4j-bloom#46]
Bloom Perspective settings done by me are not same if I access it from another browser or from another session or from another system.
lets say I have done some settings for ICONs in EDIT MODE for nodes under one_perspective though I am referring to the same perspective but trying to access it from another system rest all settings of NODES are as it is but ICONs are not visible

**Comment by GlacialBoy** [comment]
Hello @rohinibaraskar !
Which kind of deployments do you have? https://neo4j.com/docs/bloom-user-guide/current/bloom-installation/bloom-deployment-modes/
Do you have [the Bloom Plugin installed in your system](https://neo4j.com/docs/bloom-user-guide/current/bloom-installation/installation-activation/#installing-server-plugin) ?
Are you using it in Neo4j Aura?

**Comment by rohinibaraskar** [comment]
To resolve this :- 
we have to open in edit mode and then apply styling and settings of icon/color/text etc.

**Comment by ckanz** [comment]
Thanks @rohinibaraskar for sharing how you resolved the issue. There's some more information on the difference between "scene styling" and "perspective styling" here https://neo4j.com/docs/bloom-user-guide/current/bloom-tutorial/export-data/:

> Whenever you make any changes to a Scene, i.e. any changes to filters, the graph, the visualization, or the style, the Scene is automatically saved. If you switch Scene, the Scene you left is the same when you return to it.
>
> Style settings for a Scene is determined by the Perspective by default. If the style settings in your Scene deviate from this default, you can toggle between the Perspective style and the Scene style.

I will be closing this issue since it's been some time since the last reply. If you have any issues with Bloom, please feel free to raise a new issue here or on Canny https://neo4j-aura.canny.io/explore
