### ISSUE TITLE
Dismiss nodes after relationship filtering

### ISSUE THREAD

**Issue by philmcnamara** [neo4j-apps/neo4j-bloom#56]
I frequently load 1000+ nodes and relationships into the view in Bloom, and then filter the relationships via the filtering menu. When I dismiss filtered elements, the relationships disappear but the (now-unconnected) nodes remain, cluttering the view.

What is the best way to quickly remove them?

I am experimenting with scene actions on the relationships, but it seems like those are generally used to add/edit data in the scene, not dismiss it.

**Comment by joknelid** [comment]
We have a new feature in the upcoming 2.5.0 release that will let you dismiss single nodes (meaning nodes without relationships to any other node, unconnected as you say) from a context menu option. So when that is out (should be in a week max) you will be able to easily dimiss the nodes like that.

Hope that helps!

**Comment by philmcnamara** [comment]
Yeah, sounds like that will do the trick, thanks!

**Comment by adriens** [comment]
:clap: for sharing the news with the community :100:

**Comment by ckanz** [comment]
I will be closing this issue since it's been some time since the last reply and the new feature has been released. You can find out more about it here: https://neo4j.com/docs/bloom-user-guide/current/bloom-visual-tour/bloom-scene-interactions/#bloom-dismiss-single

If you have any issues with Bloom, please feel free to raise a new issue here or on Canny https://neo4j-aura.canny.io/explore
