### ISSUE TITLE
Relationship CRUD

### ISSUE THREAD

**Issue by michela** [neo4j-apps/neo4j-bloom#6]
Re. Create / Update / Delete of relationship

* How do you specify order of relationship (only one way is ever available until you create that relationship and then the order way is available from menu)  -e.g with nodes A & B "Connect A to B" but no way to get "Connect B to A"
* How do you delete a relationship?
* How do you add properties to a relationship?

**Comment by tiansivive** [comment]
Hi there.

The direction of the relationship is specified by which node you right click on to open the context menu. So if you select two nodes, `A` and `B`, and click on `B`, it will show `A->B`, wheres clicking on `A` will show `B->A`.

You can't actually *delete*  a relationship, just like you can't *delete* a node. 
If, however, all you'd like is to not visualise one or more relationships, then you can select them, right-click to open the context menu and click on the `Dismiss` action.

Adding *new* properties to relationships is currently not available, it's something we've discussed. However, you can edit already existing properties. Just double click the relationship, or right-click and press `inspect`. It should show up on the left, in the relationship inspector. If you hover any property that shows up there, you'll see an edit option. Assuming of course, you have the required role in the database.

Cheers

**Comment by michela** [comment]
>However, you can edit already existing properties

You can't delete properties in date() format

**Comment by ckanz** [comment]
Hi @michela, I'm not sure if it is still relevant to you, but I'm happy to say it is now possible to fully create, edit and delete nodes and relationships (including date and time properties). You can find out more about it in our docs here: https://neo4j.com/docs/bloom-user-guide/current/bloom-tutorial/edit-graph-data/

I will be closing this issue since it's been some time since the last reply. If you have any issues with Bloom, please feel free to raise a new issue here or on Canny https://neo4j-aura.canny.io/explore
