### ISSUE TITLE
Bloom query doesn't accept arbitrary String value as arg of search phrase?

### ISSUE THREAD

**Issue by complyue** [neo4j-apps/neo4j-bloom#71]
It happens "WITH" search suggestions:

![image](https://github.com/neo4j-devtools/neo4j-bloom/assets/15646573/325ba33c-4fe6-4a59-99b6-4532ca42679f)

![image](https://github.com/neo4j-devtools/neo4j-bloom/assets/15646573/10af31d9-e655-4a58-851a-696f22288bda)

Or "WITHOUT" search suggestions too:

![image](https://github.com/neo4j-devtools/neo4j-bloom/assets/15646573/fd0dfa90-e026-4f4a-9511-8efbc8673e46)

![image](https://github.com/neo4j-devtools/neo4j-bloom/assets/15646573/4a3c7444-ad9e-46ee-b6e5-ed9e4106fe1c)

**Comment by ckanz** [comment]
Hi @complyue! Thank you for reporting this.
It appears there's indeed a bug in the search bar when it comes to handling search phrase parameters. When pasting or fully typing out search phrase parameters, Bloom's search does not seem to recognize the parameter as fully provided. Until this is fixed, a workaround is to press the tab key after pasting the message id and before running the search. I hope this helps in the meantime until the bug is fixed.
Please let me know if you have other questions. Thank you again for taking the time to report this.

**Comment by ckanz** [comment]
Hi @complyue, I just tested with the latest release and can confirm that a fix for this has been released.

I will be closing this issue, but if you have any other issues with Bloom, please feel free to raise a new issue here or on Canny https://neo4j-aura.canny.io/explore

**Comment by complyue** [comment]
Hi @ckanz, could you be more specific about the "latest" release? The publicly available bloom atm, via Neo4j Desktop 1.5.9 is still Bloom 2.11.0, doesn't seem to have the fix incorporated.
